create table users
(
    id                uuid primary key,
    email             varchar(320) unique,
    phone_number      varchar(32) unique,
    password_hash     varchar(255) not null,
    role              varchar(32)  not null default 'USER',
    email_verification_status varchar(32) not null default 'UNVERIFIED',
    phone_verification_status varchar(32) not null default 'UNVERIFIED',
    status            varchar(32)  not null default 'ACTIVE',
    created_at        timestamptz  not null,
    updated_at        timestamptz  not null
);

create table subscription_plans
(
    id      bigint generated by default as identity primary key,
    code    varchar(64)  not null unique,
    name    varchar(128) not null,
    free    boolean      not null default true
);

create table subscriptions
(
    id         bigint generated by default as identity primary key,
    user_id    uuid        not null,
    plan_id    bigint      not null references subscription_plans (id),
    status     varchar(32) not null default 'ACTIVE',
    started_at timestamptz not null,
    expires_at timestamptz
);

create table refresh_tokens
(
    id         uuid primary key,
    user_id    uuid         not null references users (id),
    token_hash varchar(255) not null unique,
    expires_at timestamptz  not null,
    revoked_at timestamptz,
    created_at timestamptz  not null
);

create index idx_subscriptions_user_id on subscriptions (user_id);
create index idx_subscriptions_plan_id on subscriptions (plan_id);
create index idx_subscriptions_status on subscriptions (status);
create index idx_refresh_tokens_user_id on refresh_tokens (user_id);
create index idx_refresh_tokens_expires_at on refresh_tokens (expires_at);
