-- Subscription domain tables for Phase 5 billing infrastructure.
-- Expands existing subscription_plans and subscriptions tables.
-- Creates new tables for pricing, features, localization, invoices, payments, and events.

-- ============================================================
-- 1. Expand subscription_plans
-- ============================================================
alter table subscription_plans
    add column if not exists active           boolean      not null default true,
    add column if not exists grace_period_days integer    not null default 7,
    add column if not exists created_at      timestamptz  not null default now(),
    add column if not exists updated_at      timestamptz  not null default now();

-- ============================================================
-- 2. Rename subscriptions → user_subscriptions and expand
-- ============================================================
alter table subscriptions rename to user_subscriptions;

alter table user_subscriptions
    add column if not exists cancel_at_period_end boolean   not null default false,
    add column if not exists grace_period_end     timestamptz,
    add column if not exists grace_reason         varchar(64),
    add column if not exists locked_price_id      bigint,
    add column if not exists version              bigint     not null default 0,
    add column if not exists created_at           timestamptz not null default now(),
    add column if not exists updated_at           timestamptz not null default now();

-- Rename started_at → period_start, expires_at → period_end
alter table user_subscriptions rename column started_at to period_start;
alter table user_subscriptions rename column expires_at to period_end;

-- NOTE: unique constraint on user_id is added in V22 after data consolidation

-- ============================================================
-- 3. subscription_prices
-- ============================================================
create table subscription_prices
(
    id                   bigint generated by default as identity primary key,
    plan_id              bigint       not null references subscription_plans (id),
    billing_period_days  integer      not null,
    amount               numeric(12)  not null,
    currency             varchar(3)   not null,
    badge                varchar(32),
    active               boolean      not null default true,
    valid_from           timestamptz  not null default now(),
    valid_until          timestamptz,
    created_at           timestamptz  not null default now(),

    constraint uk_plan_period_currency unique (plan_id, billing_period_days, currency)
);

create index idx_subscription_prices_plan_active on subscription_prices (plan_id, active);

-- ============================================================
-- 4. subscription_features
-- ============================================================
create table subscription_features
(
    key         varchar(64)  primary key,
    description varchar(255) not null,
    active      boolean      not null default true,
    created_at  timestamptz  not null default now()
);

-- ============================================================
-- 5. plan_features
-- ============================================================
create table plan_features
(
    id          bigint generated by default as identity primary key,
    plan_id     bigint       not null references subscription_plans (id),
    feature_key varchar(64)  not null references subscription_features (key),
    enabled     boolean      not null default true,
    created_at  timestamptz  not null default now(),

    constraint uk_plan_feature unique (plan_id, feature_key)
);

-- ============================================================
-- 6. plan_localizations
-- ============================================================
create table plan_localizations
(
    id                bigint generated by default as identity primary key,
    plan_id           bigint       not null references subscription_plans (id),
    locale            varchar(10)  not null,
    display_name      varchar(128) not null,
    short_description varchar(255),
    feature_summary   text,
    created_at        timestamptz  not null default now(),

    constraint uk_plan_locale unique (plan_id, locale)
);

-- ============================================================
-- 7. provider_price_mappings
-- ============================================================
create table provider_price_mappings
(
    id                          bigint generated by default as identity primary key,
    subscription_price_id       bigint       not null references subscription_prices (id),
    provider                    varchar(32)  not null,
    environment                 varchar(16)  not null,
    provider_product_id         varchar(128),
    provider_price_id           varchar(128),
    provider_amount_override    numeric(12),
    provider_currency_override  varchar(3),
    active                      boolean      not null default true,
    created_at                  timestamptz  not null default now(),

    constraint uk_price_provider_env unique (subscription_price_id, provider, environment)
);

-- ============================================================
-- 8. invoices
-- ============================================================
create table invoices
(
    id                     uuid primary key default gen_random_uuid(),
    user_id                uuid         not null references users (id),
    plan_id                bigint       not null references subscription_plans (id),
    period_start           timestamptz  not null,
    period_end             timestamptz  not null,
    amount_due             numeric(12)  not null,
    currency               varchar(3)   not null,
    amount_after_discount  numeric(12)  not null,
    discount_currency      varchar(3)   not null,
    status                 varchar(16)  not null default 'OPEN',
    promotion_code         varchar(64),
    manual                 boolean      not null default false,
    created_at             timestamptz  not null default now(),
    updated_at             timestamptz  not null default now()
);

create index idx_invoices_user_status on invoices (user_id, status);
create index idx_invoices_user_period on invoices (user_id, period_start, period_end);

-- ============================================================
-- 9. payment_attempts
-- ============================================================
create table payment_attempts
(
    id                 uuid primary key default gen_random_uuid(),
    invoice_id         uuid         not null references invoices (id),
    provider           varchar(32)  not null,
    client_ref_id      varchar(128) not null unique,
    provider_code      varchar(128),
    provider_ref_id    varchar(128),
    amount             numeric(12)  not null,
    currency           varchar(3)   not null,
    status             varchar(24)  not null default 'PENDING',
    reversible         boolean      not null default false,
    provider_request_id varchar(128),
    created_at         timestamptz  not null default now(),
    updated_at         timestamptz  not null default now()
);

create index idx_payment_attempts_invoice on payment_attempts (invoice_id);
create index idx_payment_attempts_status on payment_attempts (status);

-- ============================================================
-- 10. subscription_events
-- ============================================================
create table subscription_events
(
    id                       bigint generated by default as identity primary key,
    user_id                  uuid         not null,
    transition_type          varchar(64)  not null,
    source_type              varchar(32)  not null,
    source_id                varchar(128) not null,
    idempotency_key          varchar(256) not null unique,

    -- Before snapshot
    status_before            varchar(32),
    plan_id_before           bigint,
    period_start_before      timestamptz,
    period_end_before        timestamptz,
    cancel_at_period_end_before boolean,
    grace_period_end_before  timestamptz,
    grace_reason_before      varchar(64),

    -- After snapshot
    status_after             varchar(32),
    plan_id_after            bigint,
    period_start_after       timestamptz,
    period_end_after         timestamptz,
    cancel_at_period_end_after boolean,
    grace_period_end_after   timestamptz,
    grace_reason_after       varchar(64),

    -- Actor and reason
    actor_id                 uuid,
    reason                   varchar(255),
    created_at               timestamptz  not null default now()
);

create index idx_subscription_events_user on subscription_events (user_id, created_at);
create index idx_subscription_events_source on subscription_events (source_type, source_id);
