-- V23: Address staff review findings — add ManualGrant, PaymentEvent, OutboxEvent,
-- provider indexes, check constraints, and fail-safe migration for duplicate subscriptions.

-- ============================================================
-- 1. manual_grants table
-- ============================================================
create table manual_grants
(
    id              uuid primary key default gen_random_uuid(),
    user_id         uuid         not null references users (id),
    plan_id         bigint       not null references subscription_plans (id),
    duration_days   integer,
    expires_at      timestamptz,
    reason          varchar(64)  not null,
    reason_note     text,
    granted_by      uuid         not null references users (id),
    revoked_at      timestamptz,
    revoked_by      uuid         references users (id),
    revoke_reason   text,
    created_at      timestamptz  not null default now()
);

create index idx_manual_grants_user on manual_grants (user_id);

-- ============================================================
-- 2. payment_events table
-- ============================================================
create table payment_events
(
    id                 bigint generated by default as identity primary key,
    payment_attempt_id uuid         references payment_attempts (id),
    provider           varchar(32)  not null,
    event_type         varchar(64)  not null,
    provider_ref_id    varchar(128),
    raw_payload        jsonb,
    safe_summary       jsonb,
    created_at         timestamptz  not null default now()
);

create index idx_payment_events_attempt on payment_events (payment_attempt_id);
create index idx_payment_events_provider_ref on payment_events (provider, provider_ref_id)
    where provider_ref_id is not null;

-- ============================================================
-- 3. outbox_events table
-- ============================================================
create table outbox_events
(
    id              bigint generated by default as identity primary key,
    event_type      varchar(128) not null,
    aggregate_type  varchar(64)  not null,
    aggregate_id    varchar(128) not null,
    payload         jsonb        not null,
    status          varchar(16)  not null default 'PENDING',
    retry_count     integer      not null default 0,
    next_retry_at   timestamptz,
    published_at    timestamptz,
    last_error      text,
    created_at      timestamptz  not null default now()
);

create index idx_outbox_events_status_retry on outbox_events (status, next_retry_at);
create index idx_outbox_events_aggregate on outbox_events (aggregate_type, aggregate_id);

-- ============================================================
-- 4. Provider reference indexes and uniqueness
-- ============================================================
-- Unique constraint on (provider, provider_ref_id) when not null
create unique index uk_payment_attempt_provider_ref
    on payment_attempts (provider, provider_ref_id)
    where provider_ref_id is not null;

-- Index on provider_code for reconciliation lookups
create index idx_payment_attempt_provider_code
    on payment_attempts (provider, provider_code)
    where provider_code is not null;

-- Index for provider+environment lookup
create index idx_provider_price_mappings_lookup
    on provider_price_mappings (subscription_price_id, provider, environment, active);

-- ============================================================
-- 5. Check constraints for data integrity
-- ============================================================
-- provider_amount_override must be both null or both non-null
alter table provider_price_mappings
    add constraint ck_provider_amount_override_complete
    check (
        (provider_amount_override is null and provider_currency_override is null)
        or
        (provider_amount_override is not null and provider_currency_override is not null)
    );

-- Non-negative money checks
alter table subscription_prices
    add constraint ck_subscription_price_amount_non_negative
    check (amount >= 0);

alter table invoices
    add constraint ck_invoice_amount_due_non_negative
    check (amount_due >= 0),
    add constraint ck_invoice_amount_after_discount_non_negative
    check (amount_after_discount >= 0);

alter table payment_attempts
    add constraint ck_payment_attempt_amount_non_negative
    check (amount >= 0);

alter table provider_price_mappings
    add constraint ck_provider_amount_override_non_negative
    check (provider_amount_override is null or provider_amount_override >= 0);

-- ============================================================
-- 6. Manual grants index for active grant lookup
-- ============================================================
create index idx_manual_grants_user_active
    on manual_grants (user_id, revoked_at, expires_at)
    where revoked_at is null;
