-- V27: Add outbox event consumer tracking for idempotent event processing.
-- Allows multiple consumers (entitlement invalidator, outbox publisher, etc.)
-- to independently track which events they have processed.

create table outbox_event_consumptions (
    id              bigint generated by default as identity primary key,
    event_id        bigint       not null references outbox_events (id),
    consumer_name   varchar(64)  not null,
    processed_at    timestamptz  not null default now(),

    constraint uk_event_consumer unique (event_id, consumer_name)
);

create index idx_outbox_event_consumptions_consumer on outbox_event_consumptions (consumer_name, processed_at);
