-- Promotion-code infrastructure for Phase 5 checkout and manual-grant support.

create table promotions
(
    id                         bigint generated by default as identity primary key,
    code                       varchar(64)    not null,
    type                       varchar(32)    not null,
    value                      numeric(12, 2) not null,
    applicable_plan_id         bigint references subscription_plans (id),
    starts_at                  timestamptz    not null,
    ends_at                    timestamptz,
    max_redemptions            integer,
    per_user_redemption_limit  integer        not null default 1,
    active                     boolean        not null default true,
    internal_notes             text,
    created_at                 timestamptz    not null default now(),
    updated_at                 timestamptz    not null default now(),
    version                    bigint         not null default 0,

    constraint uk_promotions_code unique (code),
    constraint ck_promotions_code_normalized check (code = upper(trim(code))),
    constraint ck_promotions_value_positive check (value > 0),
    constraint ck_promotions_redemption_limits check (
        (max_redemptions is null or max_redemptions > 0)
        and per_user_redemption_limit > 0
    ),
    constraint ck_promotions_window check (ends_at is null or ends_at > starts_at)
);

create index idx_promotions_code on promotions (code);
create index idx_promotions_active_window on promotions (active, starts_at, ends_at);

create table promotion_redemptions
(
    id                    uuid primary key default gen_random_uuid(),
    user_id               uuid        not null references users (id),
    promotion_id          bigint      not null references promotions (id),
    subscription_id       bigint references user_subscriptions (id),
    payment_attempt_id    uuid references payment_attempts (id),
    invoice_id            uuid references invoices (id),
    provider              varchar(32),
    redeemed_at           timestamptz,
    reserved_at           timestamptz not null,
    reservation_expires_at timestamptz not null,
    released_at           timestamptz,
    status                varchar(24) not null default 'RESERVED',
    idempotency_key       varchar(255),
    safe_audit_reference  varchar(128) not null,
    created_at            timestamptz not null default now(),

    constraint ck_promotion_redemption_reference check (
        subscription_id is not null
        or payment_attempt_id is not null
        or invoice_id is not null
    ),
    constraint ck_promotion_redemption_status_dates check (
        (status = 'RESERVED' and redeemed_at is null and released_at is null)
        or (status = 'REDEEMED' and redeemed_at is not null and released_at is null)
        or (status = 'RELEASED' and redeemed_at is null and released_at is not null)
    )
);

create index idx_promotion_redemptions_user_promotion
    on promotion_redemptions (user_id, promotion_id);

create index idx_promotion_redemptions_promotion
    on promotion_redemptions (promotion_id);

create index idx_promotion_redemptions_status_expiry
    on promotion_redemptions (promotion_id, status, reservation_expires_at);

create unique index uk_promotion_redemption_idempotency
    on promotion_redemptions (user_id, promotion_id, idempotency_key)
    where idempotency_key is not null;

create unique index uk_promotion_redemption_invoice
    on promotion_redemptions (promotion_id, invoice_id)
    where invoice_id is not null;
