create table subscription_renewal_reminders
(
    id              bigint generated by default as identity primary key,
    subscription_id bigint      not null references user_subscriptions (id),
    period_end      timestamptz not null,
    reminded_at     timestamptz not null default now(),
    unique (subscription_id, period_end)
);

create index if not exists idx_user_subscriptions_status_period_end
    on user_subscriptions (status, period_end);
create index if not exists idx_user_subscriptions_status_grace_end
    on user_subscriptions (status, grace_period_end) where grace_period_end is not null;
create index if not exists idx_payment_attempts_status_created
    on payment_attempts (status, created_at);
create index if not exists idx_outbox_events_published_created
    on outbox_events (status, created_at);
